services:
  tesis:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    working_dir: /app
    environment:
      PYTHONUNBUFFERED: "1"  
      PYTHONPATH: "/app" 
    command: python src/main.py 
